version: 2.1

orbs:
<<<<<<< HEAD
  security-report: dreamquark-ai/security-report@1.0.1

executors:
  security-report: dreamquark-ai/security-report@1.0.1
=======
  security-report: dreamquark-ai/security-report@dev:1.0.1

executors:
  security-report: dreamquark-ai/security-report@dev:1.0.1
>>>>>>> Updated config.yml

jobs:
  security-report-example:
    executor: security-report/default
    working_directory: /root/ci-example
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
          version: 20.10.2
      - run:
          name: "Build & pull the images for security report"
          command: |
            docker pull python:3.8-buster
            docker build -t python:security-test -f example/Dockerfile .
            
      - security-report/security-report:
          image: 'python'
          base-tag: '3.8-buster'
          new-tag: 'security-test'
          orga: 'PaulBarrie'
          repo: 'ci-security-report-example'
          topic: 'circleci-example'

workflows:
  CI-security-test:
    jobs:
      - security-report-example:
          context: security-report-example